### PR TITLE
OpenPGP public key signing/decryption support

### PR DESCRIPTION
**Pull request by folbricht**
Implements #2

### CODE REVIEW

**Comment by charles-dyfis-net** [comment]
I'll build an aptly patch to make use of this, and report back on any issues.

**Comment by folbricht** [comment]
There's an issue with the signing process by the looks. It uses `time.Now()` basically which changes the KeyID. So I'll have to change the command to also read the OpenPGP public key (created during the `generate` subcommand) to use its timestamp.

**Comment by folbricht** [comment]
That should be fixed as well now. It seems functional, just missing docs at this point. But I'll let you try it out first in case larger changes still have to be made.

**Comment by charles-dyfis-net** [comment]
Hmm. This is easy to implement for detached signatures. Cleartext signatures (which, alas, are used for Debian index files) look like another place where the upstream library expects a literal private key passed in... though admittedly I haven't looked past the documentation and into the source for golang.org/x/crypto/openpgp/clearsign yet.

**Comment by folbricht** [comment]
I think it calls the same `Sign()` function which should work for a crypto.Signer: https://github.com/golang/crypto/blob/0c34fe9e7dc2486962ef9867e3edb3503537209f/openpgp/packet/signature.go#L521

Will try that, and perhaps add another `clear-sign` subcommand. Let's review the command syntax once it's in, perhaps I should add the classic sign functionality as well rather than only supporting detached and clearsign signatures.

**Comment by charles-dyfis-net** [comment]
Ahh -- looking closer, I see what you mean; the result of calling `packet.NewSignerPrivateKey` should be workable here, as long as its hash algorithm is correct.

**Comment by charles-dyfis-net** [comment]
Yup, worked nicely; apologies for the alarmism above. Can I check in an amended version of this PR with a `-c` option on `tpmk openpgp sign` somewhere?

**Comment by folbricht** [comment]
I'm about to push a commit that adds -c to the sign command.

**Comment by folbricht** [comment]
A few possible TODO:
- Improve the library to build an openpgp.Entity from a public key and a TPM key, rather than handle them both independently
- Add documentation
- Consider supporting regular (non-detached) signatures as well
- Options to configure the hash function (needed?)

**Comment by charles-dyfis-net** [comment]
So, this is bizarre.

Code builds fine for me, _including_ the aptly draft PR using it (https://github.com/aptly-dev/aptly/pull/955). However, [in aptly's CI](https://travis-ci.org/github/aptly-dev/aptly/jobs/766728571)...

```none
../../../../pkg/mod/github.com/folbricht/tpmk@v0.1.2-0.20210411225238-7061339773c3/openpgp.go:58:69: config.DefaultHash.String undefined (type crypto.Hash has no field or method String)
```

...even though they're using the same v0.0.0-20190320223903-b7391e95e576 release of golang.org/x/crypto that tpmk is.

**Comment by folbricht** [comment]
The `String()` method was introduced in Go 1.15 https://golang.org/pkg/crypto/#Hash.String. I'll have to update the version in go.mod to match that.

**Comment by folbricht** [comment]
I changed the internal methods a little to make it possible to read a key from disk and attach the private key to an openpgp.Entity. This allows library users to operate on data with the standard lib functions. It didn't change the command line interface.

**Comment by folbricht** [comment]
Since someone actually fixed the openpgp library to support crypto.Decryptor keys, it was pretty straightforward to add decryption as well. Might be useful. So there are now 3 sub-commands (generate, sign, decrypt).

**Pull request merged**
